src/ImageProcessor.Web/Helpers/ProcessQueryStringEventArgs.cs
src/ImageProcessor.Web/HttpModules/ImageProcessingModule.cs
src/TestWebsites/MVC/Global.asax.cs

I use a different folder to store the images I need to be watermarked. So I need the RawUrl of the request to determine if a watermark is needed on that image.
Thanks for the great library!

Modify RequestQuerystringEvent to pass request.RawUrl

---

build/NuSpecs/ImageProcessor.Web.Plugins.AzureBlobCache.nuspec

If you install ImageProcessor.Web.Plugins.AzureBlobCache without ImageProcessor.Web.Config it doesn't work as it's not registered in web.config hence adding it as a dependency

Add NuGet dependency on ImageProcessor.Web.Plugins.AzureBlobCache

---

src/ImageProcessor/Imaging/Colors/Color32.cs

Just something I noticed while looking into it..
The URI thing failing on `:` seems to make sense though btw, at least Windoes 8 doesn't allow usage of that char in paths.

Remove unnecessary assignment/checks from Color32

---

src/ImageProcessor.Web/HttpModules/ImageProcessingModule.cs

Accordingly to this SO issue (http://stackoverflow.com/questions/30075396/http-module-intercept-requests-and-breaks-custom-errors-configuration), if I was trying to use a special URL to simulate an attack on the webapp (for example, .../App/<c), the custom error pages didn't reacted anymore.

Used the Unvalidated version of RawUrl

---

src/ImageProcessor.UnitTests/ImageFactoryUnitTests.cs
src/ImageProcessor/ImageFactory.cs

I found myself writing a lot of code similar to this
```
var bytes = File.ReadAllBytes(...)
using (var memStream = new MemoryStream(bytes)) { // extraneous
...
imageFactory.Load(memStream)
}
```
This overload removes the need to create an extra memory stream, since ImageFactory.Load already contains ones internally.

Add overload for loading image data from a byte array.

---

src/ImageProcessor.Web/HttpModules/ImageProcessingModule.cs

There was a problem with the preset parameters. After changing the preset name in the Query String, the "preset =" value persisted. This problem meant that the preset settings were not all supported by ImageProcessor.

Remove "preset=" from queryString

---

src/Plugins/ImageProcessor.Web/ImageProcessor.Web.Plugins.AzureBlobCache/AzureBlobCache.cs

Added the functionality mentioned here
https://github.com/JimBobSquarePants/ImageProcessor/issues/161
I tested it locally and all looked good but it would be worth having a quick look and testing your side. 
If no config setting is present, the behaviour stays as is. If the setting is present and is set to anything other than true/True, the behaviour stays. Otherwise, it streams the image.
<setting key="StreamCachedImage" value="true" />
Any issues, let me know
G

Allow streaming or redirecting of cached image via Azure

---

src/ImageProcessor.Web/Helpers/RemoteFile.cs

The response is always null when a 404 WebException is thrown, so the error handling was never performed.
Using ex.Response works as expected.

Fix 404 error handling in RemoteFile

---

src/ImageProcessor.UnitTests/ImageProcessor.UnitTests.csproj
src/ImageProcessor.UnitTests/Imaging/Helpers/ImageMathsUnitTests.cs
src/ImageProcessor/Imaging/Helpers/ImageMaths.cs

Original code was using a bad stackoverflow answer that didn't work when you tried to rotate around a center point that wasn't 0, 0. This can be observed by running the new unit tests in the old version of the code.

Fix for ImageMaths.RotatePoint + added tests

---

src/ImageProcessor.UnitTests/ImageProcessor.UnitTests.csproj
src/ImageProcessor.UnitTests/Imaging/Colors/CmykColorTests.cs
src/ImageProcessor/Imaging/Colors/RGBAColor.cs
src/ImageProcessor/Imaging/Colors/YCbCrColor.cs

More tests need to be added.
Due to the the static analyzer saying some of the implicit operators were unusable due to ambiguousness, and per http://stackoverflow.com/questions/25775645/ambiguous-implicit-user-defined-conversions-in-net, I removed some implicit operators that were converting to other colors types.

Added CmykColorTests.cs

---

src/ImageProcessor.UnitTests/ImageProcessor.UnitTests.csproj
src/ImageProcessor.UnitTests/Imaging/Colors/RgbaColorTests.cs
src/ImageProcessor/Imaging/Colors/HSLAColor.cs
src/ImageProcessor/Imaging/Colors/YCbCrColor.cs

Same idea as the CmykColorTests, this provides tests to uncover the issue then cleans up implicit operators so they no longer conflict.

Added Rgba Color tests and cleanup of implicit operators

---

imageprocessor/imagefactory/resize.html

How to pass a single dimension was ambiguous, due to the various possible assumptions.   Required reading the source or going and actually testing the api to find what the implemented behavior was.

Clarify how to omit a dimension for resize

---

src/ImageProcessor/ImageFactory.cs

`FormatUtilities.GetFormat` works on memoryStream because it seekable.
`memoryStream.Position = 0;` removed because `FormatUtilities.GetFormat` does it.

fix #253. ImageFactory.Load(Stream) Does not support unseekable streams.

---

appveyor.yml

The forces AppVeyor MSBuild to use CoreClr x64 RC1 when building ImageProcessor.sln

Specify that MSBuild v14 use CoreClr RC1 for build

---

src/ImageProcessor.UnitTests/ImageFactoryUnitTests.cs
src/ImageProcessor/Imaging/Resizer.cs

Fixes issue #273 where Resizing with only one dimension specified in BoxPad
mode would result in a blank image

Fix for Resizing against one dimension with BoxPad

---

src/ImageProcessor/Colors/ColorTransforms.cs
src/ImageProcessor/Colors/Colorspaces/CieLab.cs
tests/ImageProcessor.Tests/Colors/ColorConversionTests.cs

Hi Jim,
Here is a branch that contains the CIE Lab color space and the tests that go with it, to go with #260.
Hopefully nobody else was already working on this. I hope I properly followed your suggestions posted in regards to the CIE xyz space, but since the RGB conversions for Lab seem to go through xyz, you may want my branch refactored to use the XYZ functions once those are in. In any case, let me know. 
The test values I used were matched against ColorMine.

Colorspace CIE Lab

---

src/ImageProcessor/Colors/ColorTransforms.cs
src/ImageProcessor/Colors/Colorspaces/CieXyz.cs
tests/ImageProcessor.Tests/Colors/ColorConversionTests.cs

Hi Jim, here is the updated XYZ code + tests that match ColorMine.
However I noticed a couple of things that I did not know how you wanted to handle:
There are tests I copied that try to generate random RGB colours and then match them against the converted XYZ, Lab, Hsv, etc. I believe there are a couple of issues here:
1) Code is using Random.next(1) to create the values, which returns an integer only, not a number between 0 and 1;
2) Once I corrected the above, then I started to come across problems with the different implementations of Equals() for the Color Space structs - some try to perform exact matches using Vector4.Equals() (which fails a lot of the time due to floating point calculations), some do Equals() using epsilons.
So I was not sure how you wanted to deal with this, so …

XYZ code updated, tests working against ColorMine.org.

---

src/ImageProcessor.Web/Helpers/QuerystringParser/Converters/GenericConvertableConverter.cs

The culture was not passed to Convert.ChangeType, which caused issues with float parsing when running on cultures where comma is the decimal separator. The culture parameter (which is correctly passed as InvariantCulture ensures that the correct parsing rules are used.

Fix #305, broken float parsing on non en-US cultures

---

src/ImageProcessorCore/Common/Extensions/ByteExtensions.cs
src/ImageProcessorCore/Formats/Png/PaletteIndexReader.cs

Fix for loading indexed png files
this is my test image (it represents precipitation over Europe at some point in time):

Shutdown256 patch 1

---

src/ImageProcessor.Web/HttpModules/ImageProcessingModule.cs
src/ImageProcessor/Common/Extensions/ImageExtensions.cs
src/ImageProcessor/ImageFactory.cs
src/ImageProcessor/ImageProcessor.csproj
src/ImageProcessor/Imaging/AnimationProcessMode.cs
src/ImageProcessor/Imaging/Formats/GifDecoder.cs
src/ImageProcessor/Imaging/Formats/GifFormat.cs
src/ImageProcessor/Imaging/Formats/IAnimatedImageFormat.cs
src/ImageProcessor/Imaging/Resizer.cs
src/ImageProcessor/Processors/Overlay.cs
src/ImageProcessor/Processors/Resize.cs

Learned some stuff about the code and noticed that what's handled in `GifDecoder` gets sent to `ImageExtensions.Copy`, sweet! So only need to update code in one place (I should've known).
So, this is just starting the conversation and explains a bit of what I've tried:
- I tried taking 10 frames from that giant 694 frame GIF and making an animation out of that with disastrous results (so this took frame number 0, 69, 69x2, 69x3, etc until 69x10 and mashed them together): 
- I don't think processing many more than 10 frames is a very good idea, if there's many gifs, it will be rough on CPU/memory. 
- Decided to stick with just showing the first frame
- This is currently hardcoded but needs to be configurable from querystring (please advise, not sure how to get the variable in the …

OutOfMemory exception processing animated GIF #308

---

src/ImageProcessor/ImageProcessor.csproj

Remove duplicate file reference in .csproj from previous merge

Fix failing ImageProcessor project build

---

src/ImageProcessorCore/Formats/Jpg/JpegEncoder.cs
src/ImageProcessorCore/Formats/Jpg/JpegEncoderCore.cs
src/ImageProcessorCore/Formats/Jpg/JpegSubsample.cs

Add support for 444 encoding in jpeg encoder.  Use it by default (if not set) when quality is gte 80.

Add 4:4:4 encoding to jpeg encoder.

---

src/ImageProcessor.Web/Caching/IImageCache.cs
src/ImageProcessor.Web/Caching/ImageCacheBase.cs
src/ImageProcessor.Web/Configuration/ImageCacheSection.cs
src/ImageProcessor.Web/Configuration/ImageProcessorConfiguration.cs
src/ImageProcessor.Web/Configuration/Resources/cache.config.transform
src/ImageProcessor.Web/HttpModules/ImageProcessingModule.cs
tests/ImageProcessor.TestWebsite/config/imageprocessor/cache.config

For the project I am looking to use this tool for, I want to cache the disk based images for a long time (a year is a good default), however I need to make sure the browser cache expires in a reasonable amount of time and attempts to re-validate the image with the source in case it has changed. The code currently sends a value of 365 days for the images to be cached in the browser, so if an image is update before it expires in the browser, the user won't ever see the updated version.
Hence I think it is better to separate the amount of time it is cached on disk, and the amount of time it is cached in the browser.
I also fixed the expiration time stamp for the disk cache, and fixed the MVC sample project.
I also fixed up compile issues for the Framework branch and recovered missing images. …

Support for separate disk cache and bug fixes

---

src/ImageProcessor.Web/Helpers/ValidatingRequestEventArgs.cs
src/ImageProcessor.Web/HttpModules/ImageProcessingModule.cs
src/ImageProcessor.Web/ImageProcessor.Web.csproj

Creates a cancelable event to validate the request IP does the processing. This can be used to cancel the request based on parameters or to directly manipulate the parameters. This deprecates the ProcessQuerystringEventHandler and ProcessQuerystringEventHandler since events should not really return an object like string since that means multiple event handlers cannot effectively subscribe, instead the event should contain an args object that can be manipulated by multiple handlers if they are registered.

Creates a cancelable event to validate the request

---

src/ImageProcessorCore/project.json
tests/ImageProcessorCore.Benchmarks/project.json
tests/ImageProcessorCore.Tests/project.json

With these changes the project compiles against netstandard 1.1 which increases the number of platforms it can be used on by a lot  (see [platforms](https://github.com/dotnet/corefx/blob/master/Documentation/architecture/net-platform-standard.md)). The test project is compiled against netcoreapp1.0 and therefor runs on both the full framework as well as .net core. BenchmarkDotNet unfortunately only supports the full framework so I had to go with .net 4.5.1 for it.

Fix project.json files

---

src/ImageProcessorCore/project.json

This replaces the "NETStandard.Library" reference with individual references to the libraries that are actually used from the standard library. This gives people who are consuming the package the freedom to be more granular about their dependencies.

Explicitly list individual NuGet dependencies

---

src/ImageProcessor.Web.Plugins.AzureBlobCache/AzureBlobCache.cs

Fix for #428 
Maps HTTP headers between browser and Azure CDN to enable automatic handling of 304s

304 passthrough for AzureBlobCache.streamCachedImage

---

NuGet.config
tests/ImageProcessorCore.Benchmarks/Config.cs
tests/ImageProcessorCore.Benchmarks/Program.cs
tests/ImageProcessorCore.Benchmarks/Properties/AssemblyInfo.cs
tests/ImageProcessorCore.Benchmarks/project.json

Hello!
You have  reported a [bug in BenchmarkDotNet repo](https://github.com/PerfDotNet/BenchmarkDotNet/issues/231). 
I have now fixed it. The problem is that we will not ship next version soon, so I added link to our development feed to use the latest dll with the fix.
Extras:
- `BenchmarkSwitcher` can accept `Assembly` now so you don't need to mess with the reflection on your own
- I added an assembly-wide config for you, so if you want to use some Diagnosers you just need to uncomment the corresponding code (I noticed your comments left in the code which said that it did not work before)
Best regards,
Adam

update to latest #BenchmarkDotNet version

---

src/ImageProcessor.Web/Caching/ImageCacheBase.cs

re #432 
As suggested, I have however added the ```AugmentSettings``` method to the base ```ImageCacheBase``` so that the S3 cache can use the same method to create the cache with custom settings resolver.

Customisation of Settings within ImageCacheBase

---

src/ImageProcessorCore/Image/ImageProperty.cs
tests/ImageProcessorCore.Tests/Image/ImagePropertyTests.cs

This pull request includes the following changes for ImageProperty :
It is no longer a struct.
Guard that the name of a property can not be null or empty.
Make sure that Equals and GetHashCode can handle a null value.
Added unit tests.

Changes to ImageProperty

---

src/ImageProcessorCore/Formats/Bmp/BmpEncoder.cs
src/ImageProcessorCore/Formats/Gif/GifEncoder.cs
src/ImageProcessorCore/Formats/Gif/GifEncoderCore.cs
src/ImageProcessorCore/Formats/IImageEncoder.cs
src/ImageProcessorCore/Formats/Jpg/JpegDecoderCore.cs
src/ImageProcessorCore/Formats/Jpg/JpegEncoder.cs
src/ImageProcessorCore/Formats/Jpg/JpegEncoderCore.cs
src/ImageProcessorCore/Formats/Png/PngEncoder.cs
src/ImageProcessorCore/Image/ImageExtensions.cs

Some of the encoders do a cast from ImageBase to Image to make sure they can access some properties. This patch changes the IImageEncoder to use Image instead of ImageBase and removes those casts.

Change encoder to use Image instead of ImageBase.

---

src/ImageProcessor.Web.Plugins.AzureBlobCache/AzureBlobCache.cs

A null reference is thrown if the original response did not have the headers.

Do a null check on headers before copying them

---

src/ImageProcessorCore/Samplers/Processors/Convolution/Convolution2DFilter.cs
src/ImageProcessorCore/Samplers/Processors/Convolution/EdgeDetection/EdgeDetector2DFilter.cs
src/ImageProcessorCore/Samplers/Processors/Convolution/EdgeDetection/KayyaliProcessor.cs
src/ImageProcessorCore/Samplers/Processors/Convolution/EdgeDetection/PrewittProcessor.cs
src/ImageProcessorCore/Samplers/Processors/Convolution/EdgeDetection/RobertsCrossProcessor.cs
src/ImageProcessorCore/Samplers/Processors/Convolution/EdgeDetection/ScharrProcessor.cs
src/ImageProcessorCore/Samplers/Processors/Convolution/EdgeDetection/SobelProcessor.cs
tests/ImageProcessorCore.Benchmarks/Samplers/DetectEdges.cs

Use jagged instead of multidimensional array as suggested in #462.
Only create the kernels once in the filters.

Use jagged instead of multidimensional array

---

src/ImageProcessor/Imaging/Formats/FormatUtilities.cs

This will also allow to have [jpegs with longer fileheaders](https://github.com/JimBobSquarePants/ImageProcessor/blob/develop/src/ImageProcessor/Imaging/Formats/JpegFormat.cs#L31)

support file header with variable length (#537)

---

build/NuSpecs/ImageProcessor.Web.nuspec
src/ImageProcessor.Web/ImageProcessor.Web.csproj
src/ImageProcessor.Web/packages.config

Looks like a new nice fix in this version: https://github.com/Microsoft/Microsoft.IO.RecyclableMemoryStream/releases/tag/v1.2.1

Update the Microsoft.IO.RecyclableMemoryStream dependency

---

src/ImageProcessor/Processors/Watermark.cs

if gif image set watermark font will fail .
because FontFamily object is Dispose .
Thanks for contributing to ImageProcessor!

fix gif add watermark font bug

---

src/ImageProcessor.Web.Plugins.PostProcessor/PostProcessor.cs

This is a minor change which eliminates anti-pattern of using Thread.Sleep() in a loop. Using Thread.Sleep() in a loop is inefficient because of unnecessary context switches and unnecessary delays that it causes.
I've found this repo by using [Google BigQuery](https://cloud.google.com/bigquery/public-data/github) when I searched if [my code analyzer](https://github.com/DotNetAnalyzers/AsyncUsageAnalyzers/pull/50) is useful.
PS. I recommend viewing this PR is a in a tool that handles changes of indentation well (e.g. git plugin for VS2017).
Prerequisites:

use ManualResetEventSlim instead of using Thread.Sleep in a loop

---

src/ImageProcessor.Web/HttpModules/ImageProcessingModule.cs

This pull request fixes cast error (`Unable to cast object of type 'SafeUrl' to type 'System.Uri'`) when CORS whitelist section is used.

Fix cast error when getting CORS whitelist

---

src/ImageProcessor.Web/Configuration/Resources/processing.config.transform
src/ImageProcessor.Web/ImageProcessor.Web.csproj
src/ImageProcessor.Web/Processors/Gamma.cs
tests/ImageProcessor.Web.UnitTests/RegularExpressionUnitTests.cs

ImageProcessor.Web is missing a Gamma IWebGrapicsProcessor implementation. The IGrapicsProcessor is there

Adds missing Gamma processor to Web

---

src/ImageProcessor.Web/Caching/CacheIndexer.cs
src/ImageProcessor.Web/Caching/ImageCacheBase.cs
src/ImageProcessor.Web/Configuration/ImageCacheSection.cs
src/ImageProcessor.Web/Configuration/ImageProcessorConfiguration.cs

I've added a new optional config property `ImageCacheSection.CachedRewritePathExpiry` and passed this in to `CacheIndexer.Add` with a default value matching the currently-hardcoded expiry time of 1 minute. This necessitates a new property `ImageCacheBase.CachedPathExpiry`.

Allow `CachedRewritePathExpiry` to be passed as a config variable

---

src/ImageProcessor.Web/Caching/CacheIndexer.cs
src/ImageProcessor.Web/Caching/ImageCacheBase.cs
src/ImageProcessor.Web/Configuration/ImageCacheSection.cs
src/ImageProcessor.Web/Configuration/ImageProcessorConfiguration.cs

- [x ] I have verified that I am following matches the existing coding patterns and practise as demonstrated in the repository. These follow strict Stylecop rules :cop:.
Amend `CachedRewritePathExpiry` to be passed as a `TimeSpan` (instead of `int`) as suggested by @dlemstra in pull request #640.
I've made the `TimeSpan` be the default, but added an overload to `CacheIndexer.Add` that takes an `int`, in case anyone has already started using the code from PR #640. The only potential **breaking change** is that I have changed the config property `ImageCacheSection.CachedRewritePathExpiry` (that I created in #640) to take a `TimeSpan` (and thus a `TimeSpan` literal like `0:1:0` for 1 minute) instead of an `int`. This uses a [`PositiveTimeSpanValidator`](https://msdn.microsoft.com/en-us/librar …

Amend `CachedRewritePathExpiry` to be passed as a `TimeSpan` (instead of `int`)

---

src/ImageProcessor/Common/Exceptions/Logging/DefaultLogger.cs

Allow logging messages without DEBUG constant or resorting to reflection using the built-in Trace class.

Changed Debug.WriteLine to Trace.WriteLine

---

src/ImageProcessor.Web/Caching/DiskCache.cs

Fixes #653
* Use the cached file modification time, rather than the creation time of the file
* Allow overwriting of existing cache files, whilst preserving the "hack" fix (catches errors rather than potentially throwing them)
* Simplify a DateTime.UtcNow reference

Fix cache break preventing cache from being used again

---

src/ImageProcessor.Web/Configuration/ImageProcessorConfiguration.cs
src/ImageProcessor.Web/Helpers/RemoteFile.cs
src/ImageProcessor.Web/HttpModules/ImageProcessingModule.cs
src/ImageProcessor.Web/ImageProcessor.Web.csproj
src/ImageProcessor.Web/Services/CloudImageService.cs
src/ImageProcessor.Web/Services/RemoteImageService.cs

Replace HttpWebRequest with HttpResponseMessage. Fixing #651 Requests are respect timeout property now.
RemoteImageService and CloudImageService now do less work per request also.

Replace HttpWebRequest with HttpResponseMessage. Fix #651

---

src/ImageProcessor.Web/Helpers/ImageHelpers.cs

the inline documentation of GetExtension says default to "string.Empty", but the code returns "jpg".
In my opinion string.Empty actually sounds more feasible.
This commits add a parameter with default value "jpg" to make it easier to check if the requested input actually is supported or not by passing f.ex. null or string.Empty as default value.

add default value for GetExtension method

---

src/ImageProcessor.Web/Configuration/ImageProcessingSection.cs
src/ImageProcessor.Web/Configuration/ImageProcessorConfiguration.cs
src/ImageProcessor.Web/Configuration/Resources/processing.config.transform
src/ImageProcessor.Web/HttpModules/ImageProcessingModule.cs
src/ImageProcessor/ImageFactory.cs
src/ImageProcessor/ImageProcessor.csproj
src/ImageProcessor/Imaging/MetaData/ExifPropertyTagConstants.cs
src/ImageProcessor/MetaDataMode.cs
tests/ImageProcessor.Playground/Program.cs
tests/ImageProcessor.TestWebsite/config/imageprocessor/processing.config

Adds a new overload to `ImageFactory` that accept the `MetaDataMode` enum.
- None
- Copyright
- Geolocation
- CopyrightAndGeolocation
- All
Additionally the Web module `processing.config` now accepts a new optional property `metaDataMode` which when used in conjunction with the existing `preserveExifMetaData` property allows more fine grained control over what properties to preserve.
e.g
``` xml
<processing preserveExifMetaData="true" metaDataMode="Copyright" fixGamma="false" interceptAllRequests="true" allowCacheBuster="true">
```
All this is done in a fully backwards-compatible manner with both properties optional. 
@hartvig @Jeavon @drobar @PeteDuncanson @Matthew-Wise Please comment below with your thoughts. 
I think I've done enough to cover the basic requirements.
I don't want to add …

Add MetaDataMode. Fix #585

---

src/ImageProcessor/ImageFactory.cs
src/ImageProcessor/Processors/Hue.cs

If rotate is false it is not possible to set a hue of 0 as the function will return immediately.
This change will add a check if rotate is true and return only if so.
Fixes #665

fix Hue when not rotating

---

src/ImageProcessor.Web/HttpModules/ImageProcessingModule.cs

ImageProessor.Web 4.9.2.19 whereby wrong MetaDataMode was being added in call to ImageFactory.
Reported in issue #669

#669 - metadata stripped after image processed 

---

src/ImageProcessor/Processors/AutoRotate.cs

System.Drawing incorrectly limits future drawing operations to the old dimensions following FlipRotate
The workaround is to clone the image.

Clone autorotated image. Fix #709

---

imageprocessor-web/plugins/azure-blob-cache.md

I added the attribute to the config sample and an explanation of what it does.

Add missing attribute "memoryMaxMinutes" to config sample

---

src/ImageProcessor.Web/Processors/EntropyCrop.cs

This is a fix for Issue #731 - I've added a cast to convert the literal 128 value into a byte within the ternary expression, this looks like it was originally removed in a bulk clean-up operation in commit [4af8de4a](https://github.com/JimBobSquarePants/ImageProcessor/commit/4af8de4a6376d9426fadd5c4596bc1de187899c0#diff-e424c650610a9bba9ed533296f341ca7).

Added byte cast to fix entropy crop web processor casting issue.

---

build/build.ps1

This fixes https://github.com/JimBobSquarePants/ImageProcessor/issues/735 (and the duplicate https://github.com/JimBobSquarePants/ImageProcessor/issues/757) by only adding the build number to the assembly version. This way the version specified in this build script and the dependencies in the nuspec-files are exact matches and won't produce warnings when consuming the packages.

Remove build number from NuGet verions

---

src/ImageProcessor.Web.Plugins.AmazonS3Cache/AmazonS3Cache.cs
src/ImageProcessor.Web.Plugins.AzureBlobCache/AzureBlobCache.cs

When the Amazon S3 and Azure Blob caches were redirecting the local request to the remote/CDN endpoints, it didn't add a `Cache-Control` header and honor the `BrowserMaxDays` setting. This makes sure the redirects are also cached with the same duration as the image itself.

Cache redirects on browser for Amazon S3 and Azure Blob cache

---

src/ImageProcessor.Web/Caching/DiskCache.cs

This fixes issue https://github.com/JimBobSquarePants/ImageProcessor/issues/794 by catching exceptions thrown while enumerating files from directories that are deleted while the cache trimming is executed (e.g. by another server running a concurrent cache trimming job or manually deleting the directory).

Fix race condition in DiskCache trimmer causing DirectoryNotFoundException

---

src/ImageProcessor.Plugins.Cair/ImageProcessor.Plugins.Cair.csproj
src/ImageProcessor.Plugins.Cair/Imaging/ContentAwareResizeLayer.cs
src/ImageProcessor.Plugins.Cair/packages.config
src/ImageProcessor/ImageProcessor.csproj
src/ImageProcessor/Imaging/Colors/CmykColor.cs
src/ImageProcessor/Imaging/Colors/Color32.cs
src/ImageProcessor/Imaging/Colors/HSLAColor.cs
src/ImageProcessor/Imaging/Colors/RGBAColor.cs
src/ImageProcessor/Imaging/Colors/YCbCrColor.cs
src/ImageProcessor/Imaging/CropLayer.cs
src/ImageProcessor/Imaging/FastBitmap.cs
src/ImageProcessor/Imaging/Filters/Photo/MatrixFilterBase.cs
src/ImageProcessor/Imaging/Formats/FormatBase.cs
src/ImageProcessor/Imaging/GaussianLayer.cs
src/ImageProcessor/Imaging/ImageLayer.cs
src/ImageProcessor/Imaging/MetaData/Rational.cs
src/ImageProcessor/Imaging/ResizeLayer.cs
src/ImageProcessor/Imaging/RoundedCornerLayer.cs
src/ImageProcessor/Imaging/TextLayer.cs
src/ImageProcessor/packages.config
tests/ImageProcessor.UnitTests/Imaging/Filters/Photo/MatrixFilterBaseTests.cs

This fixes some possible `NullReferenceException`s in the `Equals` implementations and uses `ValueTuple` to generate the hash codes, as that's a lot easier, cleaner and heavily optimized:
- https://stackoverflow.com/a/4630550
- https://intellitect.com/overidingobjectusingtuple/
- https://montemagno.com/optimizing-c-struct-equality-with-iequatable/

Fix and cleanup GetHashCode and Equals

---

src/ImageProcessor.Web/Caching/DiskCache.cs

This removes the (unnecessary) `RecursivelyDeleteEmptyDirectories()` method and removes empty directories while trimming the files (see https://github.com/JimBobSquarePants/ImageProcessor/pull/795#issuecomment-651026443).

Remove RecursivelyDeleteEmptyDirectories and fix DirectoryNotFoundException
