imageprocessor-web/imageprocessingmodule/resize.html

Documented how to use center parameter

---

src/ImageProcessor.Web/Extensions/StringExtensions.cs
src/ImageProcessor.Web/Services/RemoteImageService.cs
src/Plugins/ImageProcessor.Web/ImageProcessor.Web.Plugins.AzureBlobCache/AzureBlobCache.cs

add work-a-round for dev storage emularto url
create cache contain if it not exists

create cache contain if it not exists, add work-a-round for dev storage emularto url

---

src/ImageProcessor.Web/Helpers/ImageHelpers.cs

Dont trim if querystring is null or empty

---

src/ImageProcessor.UnitTests/ImageProcessor.UnitTests.csproj
src/ImageProcessor.UnitTests/Imaging/Filters/Photo/MatrixFilterBaseTests.cs

Is this what you're looking for RE: additional unit tests + coverage help?

Added matrix filter base tests

---

src/ImageProcessor.UnitTests/ImageProcessor.UnitTests.csproj
src/ImageProcessor.UnitTests/Processors/MetaTests.cs

Moq doesn't seem to be installed and ImageFactory is not derived from an interface so I find writing a meaningful unit test for ProcessImage to be difficult. Any thoughts on extracting an interface for testing purposes? If you agree, I can add in a meaningful unit test for that with a new pull request (unless you want integration tests).

Added MetaTests.cs, updated csproj.

---

src/ImageProcessor.UnitTests/ImageProcessor.UnitTests.csproj
src/ImageProcessor.UnitTests/Processors/QualityTests.cs

Moq doesn't seem to be installed and ImageFactory is not derived from an interface so I find writing a meaningful unit test for ProcessImage to be difficult. Any thoughts on extracting an interface for testing purposes? If you agree, I can add in a meaningful unit test for that with a new pull request (unless you want integration tests).

Add Quality tests

---

src/ImageProcessor.UnitTests/Imaging/Helpers/ImageMathsUnitTests.cs

Names for these tests might be a little wonky.

Added bounding rectangle method tests

---

src/ImageProcessor.Web.UnitTests/Extensions/DirectoryInfoExtensionsUnitTests.cs
src/ImageProcessor.Web.UnitTests/ImageProcessor.Web.UnitTests.csproj

Please verify that the setup methods do not cause horror and/or dismay

Added some directory info extension unit tests.

---

src/ImageProcessor.UnitTests/Extensions/EnumerableExtensionsUnitTests.cs
src/ImageProcessor.UnitTests/ImageProcessor.UnitTests.csproj

Only 1/2 of public methods tested

Added enumerable range extension tests

---

src/ImageProcessor.UnitTests/ImageProcessor.UnitTests.csproj
src/ImageProcessor.UnitTests/Imaging/ImageLayerUnitTests.cs
src/ImageProcessor/Imaging/ImageLayer.cs

Seem to have broken my tools that convert my preferred test naming to the project test naming. Will investigate.

Added ImageLayerUnitTests and fixed incorrect text in summary

---

src/ImageProcessor.UnitTests/ImageProcessor.UnitTests.csproj
src/ImageProcessor.UnitTests/Imaging/Quantizers/WuQuantizer/ColorMomentUnitTests.cs

Weird thing I noticed with these; weighted distance comes out as a long and chops off the decimal (effectively rounding down) however the variance uses the decimal number and returns a float. If all that sounds okay then we're good to go!

Added color moment tests

---

src/ImageProcessor.UnitTests/ImageFactoryUnitTests.cs
src/ImageProcessor.UnitTests/ImageProcessor.UnitTests.csproj
src/ImageProcessor.UnitTests/Imaging/MetaData/ExifBitConverterTests.cs
src/ImageProcessor.UnitTests/Processors/FormatTests.cs
src/ImageProcessor.Web.UnitTests/ImageProcessor.Web.UnitTests.csproj
src/ImageProcessor/ImageProcessor.csproj
src/ImageProcessor/Imaging/ComputerArchitectureInfo.cs
src/ImageProcessor/Imaging/IComputerArchitectureInfo.cs
src/ImageProcessor/Imaging/MetaData/ExifBitConverter.cs
src/ImageProcessor/Imaging/MetaData/ImageFactoryMetaExtensions.cs

I made a small internal refactor to make exifbitconverter more testable.

Additional tests for ExifBitConverter + Format

---

src/ImageProcessor.UnitTests/ImageProcessor.UnitTests.csproj
src/ImageProcessor.UnitTests/Imaging/Colors/HslaColorTests.cs
src/ImageProcessor/Imaging/Colors/RGBAColor.cs
src/ImageProcessor/Imaging/Colors/YCbCrColor.cs

Add HSLA color tests + cleanup implicit operators

Conflicts:

---

src/ImageProcessor.Web/Services/CloudImageService.cs

Addresses issue where I couldn't honour the base container url via current configurations - as per issue #234

Allows configuring in the base container

---

src/ImageProcessor.Web/PostProcessor/PostProcessor.cs

Adds try-catch for this specific exception

jpegtran errors with: "This program is blocked by group policy." #268

---

src/ImageProcessor/Colors/ColorTransforms.cs
src/ImageProcessor/Colors/Colorspaces/CieXyz.cs
tests/ImageProcessor.Tests/Colors/ColorConversionTests.cs

A "copy-paste" of the methods mentioned in issue #260 
(https://github.com/scijs/color-space/blob/master/xyz.js)

Colorspace CieXyz

---

src/ImageProcessor/Colors/ColorSpacialTransforms.cs
tests/ImageProcessor.Tests/Colors/ColorSpacialTransformTests.cs

This is a branch that satisfies some base criteria for multiply blending per issue https://github.com/JimBobSquarePants/ImageProcessor/issues/294. Discussion re: the implementation of multiply blending can continue here as work moves forward while generic information about blending can occur in the issue.
Or if this is okay as is we can merge in and investigate other modes.

Multiply blending

---

src/Plugins/ImageProcessor.Web/ImageProcessor.Web.Plugins.AzureBlobCache/AzureBlobCache.cs

workaround for https://github.com/JimBobSquarePants/ImageProcessor/issues/303

set unknown content type (but still image) as fallback when unknown

---

src/ImageProcessor/Filters/Alpha.cs
src/ImageProcessor/Filters/BackgroundColor.cs
src/ImageProcessor/Filters/Binarization/Threshold.cs
src/ImageProcessor/Filters/Blend.cs
src/ImageProcessor/Filters/Brightness.cs
src/ImageProcessor/Filters/ColorMatrix/ColorMatrixFilter.cs
src/ImageProcessor/Filters/Contrast.cs
src/ImageProcessor/Filters/Convolution/Convolution2DFilter.cs
src/ImageProcessor/Filters/Convolution/Convolution2PassFilter.cs
src/ImageProcessor/Filters/Convolution/ConvolutionFilter.cs
src/ImageProcessor/Filters/Glow.cs
src/ImageProcessor/Filters/Invert.cs
src/ImageProcessor/Filters/Pixelate.cs
src/ImageProcessor/Filters/Vignette.cs
src/ImageProcessor/IImageProcessor.cs
src/ImageProcessor/ParallelImageProcessor.cs
src/ImageProcessor/Samplers/Crop.cs
src/ImageProcessor/Samplers/EntropyCrop.cs
src/ImageProcessor/Samplers/ImageSampleExtensions.cs
src/ImageProcessor/Samplers/Resize.cs
src/ImageProcessor/Samplers/Rotate.cs
src/ImageProcessor/Samplers/RotateFlip.cs
tests/ImageProcessor.Tests/Processors/Filters/FilterTests.cs
tests/ImageProcessor.Tests/Processors/Samplers/SamplerTests.cs

Added progress updating to every filter and sampler. Integrated progress updates into existing unit tests.

Progress updates to client code

---

src/ImageProcessorCore/Colors/Color.cs
tests/ImageProcessorCore.Tests/Colors/ColorTests.cs

Added a few Color tests for constructors and optimized some (mainly unused) portions of Color.cs

Optimized Vector usage in Color just a tiny bit

---

src/ImageProcessor/ImageProcessor.csproj
src/ImageProcessor/Processors/Watermark.cs

Updated PR from #328 
Target framework branch.

Fix measure string (framework)

---

imageprocessor/plugins/webp.md

Clarified which versions of the package require which version of the c++ package since a lot of people are still using the earlier versions and might need to redeploy it on new servers.

Clarified c++ package requirements for WebP plugin

---

src/ImageProcessorCore/Formats/Jpg/JpegDecoderCore.cs

Fix to jpeg decocding, wrong size for mcu counter.

---

src/ImageProcessorCore/Samplers/Crop.cs

Crop source origin fixed

---

appveyor.yml

List out CI Build info.

---

src/ImageProcessorCore/Formats/Bmp/BmpDecoderCore.cs
tests/ImageProcessorCore.Tests/FileTestBase.cs

#392 add support for negative height in bmp files

---

src/ImageProcessor.Web/Helpers/StringHelper.cs
src/ImageProcessor.Web/HttpModules/ImageProcessingModule.cs

Adding code fix to handle non-rooted urls by replacing the ApplicationPath from the Request.Path

Adding a fix to allow non-rooted urls to work.

---

src/ImageProcessorCore/Common/Helpers/Guard.cs
src/ImageProcessorCore/Formats/Jpg/JpegDecoderCore.cs
src/ImageProcessorCore/Formats/Jpg/JpegEncoderCore.cs
src/ImageProcessorCore/Image/Image.cs
src/ImageProcessorCore/Profiles/Exif/ExifDataType.cs
src/ImageProcessorCore/Profiles/Exif/ExifParts.cs
src/ImageProcessorCore/Profiles/Exif/ExifProfile.cs
src/ImageProcessorCore/Profiles/Exif/ExifReader.cs
src/ImageProcessorCore/Profiles/Exif/ExifTag.cs
src/ImageProcessorCore/Profiles/Exif/ExifValue.cs
src/ImageProcessorCore/Profiles/Exif/ExifWriter.cs
src/ImageProcessorCore/Profiles/Exif/README.md
tests/ImageProcessorCore.Tests/FileTestBase.cs
tests/ImageProcessorCore.Tests/Helpers/GuardTests.cs
tests/ImageProcessorCore.Tests/Profiles/Exif/ExifProfileTests.cs
tests/ImageProcessorCore.Tests/Profiles/Exif/ExifValueTests.cs
tests/ImageProcessorCore.Tests/TestImages.cs

These patches will add support for reading and writing exif profiles to the JPEG encoder and decoder. The ExifProfile class can also be used by other coders in the future.

Exif support

---

tests/ImageProcessorCore.Benchmarks/General/ArrayCopy.cs

I added `Buffer.MemoryCopy` to benchmarks and also fixed the way `Unsafe` was used. 
```ini
Host Process Environment Information:
BenchmarkDotNet-Dev.Core=v0.9.9.0
OS=Microsoft Windows NT 6.2.9200.0
Processor=Intel(R) Core(TM) i7-4700MQ CPU 2.40GHz, ProcessorCount=8
Frequency=2338336 ticks, Resolution=427.6545 ns, Timer=TSC
CLR=MS.NET 4.0.30319.42000, Arch=64-bit RELEASE [RyuJIT]
GC=Concurrent Workstation
JitModules=clrjit-v4.6.1055.0
Type=ArrayCopy  Mode=Throughput  
```
Method | Count |      Median |     StdDev | Scaled | Scaled-SD | Gen 0 | Gen 1 | Gen 2 | Bytes Allocated/Op |
-------------------------------- |------ |------------ |----------- |------- |---------- |------ |------ |------ |------------------- |
**Copy using Array.Copy()** |   **100** |  **30.5768 ns** |  **0.1895 ns** | …

added Buffer.MemoryCopy to ArrayCopy benchmarks

---

src/ImageProcessorCore/Colors/Color.cs
tests/ImageProcessorCore.Tests/Colors/ColorTests.cs

- Refactored color to store the value as RGBA.
- Added FromHex and ToHex to color.

Refactored the Color struct.

---

src/ImageProcessor.Web/Helpers/RemoteFile.cs
src/ImageProcessor.Web/Services/RemoteImageService.cs

Added useragent setting to remote image service See #487

useragent setting

---

src/ImageProcessor/Imaging/ResizeLayer.cs
src/ImageProcessor/Imaging/Resizer.cs

Added ability to manually define the specific anchor point when resizing in `BoxPad` mode

Add optional anchor point to resize

---

src/ImageProcessor.Web.Plugins.AzureBlobCache/AzureBlobCache.cs

If date is utc as it is when coming from googlebot then we get parse
errors so added method to work around this

If-Modified-Since fix

---

src/ImageProcessor.Web/Caching/DiskCache.cs
src/ImageProcessor.Web/HttpModules/ImageProcessingModule.cs

This should address https://github.com/JimBobSquarePants/ImageProcessor/issues/536.

check ETag and set headers for files outside web root

---

src/ImageProcessor.Web/Caching/DiskCache.cs

fixes issue https://github.com/JimBobSquarePants/ImageProcessor/issues/544

add content-length header when using TransmitFile method

---

src/ImageProcessor.Web.Plugins.PostProcessor/PostProcessorBootstrapper.cs

Reverts JimBobSquarePants/ImageProcessor#591

Revert "Fixed #590 Delete folder-issue in Post Processor and added more granu…"

---

src/ImageProcessor/Imaging/Quantizers/WuQuantizer/PaletteColorHistory.cs

The fix is taken from philjones' PR in https://github.com/drewnoakes/nquant/pull/3.
This fixes the issue #623

fix: value of '-xyz' is not valid for 'alpha'

---

build/build.ps1
src/ImageProcessor.Web.Plugins.AmazonS3Cache/AmazonS3Cache.cs
src/ImageProcessor.Web.Plugins.AzureBlobCache/AzureBlobCache.cs
src/ImageProcessor.Web/Caching/CacheIndexer.cs
src/ImageProcessor.Web/Caching/DiskCache.cs
src/ImageProcessor.Web/Caching/ImageCacheBase.cs
src/ImageProcessor.Web/Configuration/ImageCacheSection.cs
src/ImageProcessor.Web/Configuration/ImageProcessorConfiguration.cs

Remove redundant metadata requests

---

src/ImageProcessor.Web/Helpers/RemoteFile.cs
src/ImageProcessor.Web/Services/CloudImageService.cs
src/ImageProcessor.Web/Services/RemoteImageService.cs

Use per-service HttpClient instances. Fix #690

---

build/NuSpecs/ImageProcessor.Web.PostProcessor.nuspec
build/build.ps1
src/ImageProcessor.Web.Plugins.PostProcessor/ImageProcessor.Web.Plugins.PostProcessor.csproj
src/ImageProcessor.Web.Plugins.PostProcessor/PostProcessor.cs
src/ImageProcessor.Web.Plugins.PostProcessor/PostProcessorBootstrapper.cs
src/ImageProcessor.Web.Plugins.PostProcessor/Resources/Unmanaged/x86/png.cmd

Remove child processes and optimize post process.

---

src/ImageProcessor.Web/Helpers/QuerystringParser/Converters/ColorTypeConverter.cs
src/ImageProcessor.Web/Helpers/QuerystringParser/Converters/FontFamilyConverter.cs
src/ImageProcessor.Web/Helpers/QuerystringParser/Converters/GenericArrayTypeConverter.cs
src/ImageProcessor.Web/Helpers/QuerystringParser/Converters/GenericConvertableConverter.cs
src/ImageProcessor.Web/Helpers/QuerystringParser/Converters/GenericListTypeConverter.cs
src/ImageProcessor.Web/Helpers/QuerystringParser/Converters/PointConverter.cs
src/ImageProcessor.Web/Helpers/QuerystringParser/Converters/QueryParamConverter.cs
src/ImageProcessor.Web/Helpers/QuerystringParser/Converters/SizeConverter.cs
src/ImageProcessor.Web/Helpers/QuerystringParser/QueryParamParser.cs

Better null handling

---

src/ImageProcessor.Web/HttpModules/ImageProcessingModule.cs

Capture and log ImageFormatException

---

src/ImageProcessor.Web.Plugins.AzureBlobCache/AzureBlobCache.cs

Fix issue where relative path will throw exection

Sanitise request check. Fix #604

---

build/content/ImageProcessor.Web.Plugins.AmazonS3Cache/config/imageprocessor/cache.config.transform
src/ImageProcessor.Web.Plugins.AmazonS3Cache/AmazonS3Cache.cs
src/ImageProcessor.Web.Plugins.AmazonS3Cache/ImageProcessor.Web.Plugins.AmazonS3Cache.csproj
src/ImageProcessor.Web.Plugins.AmazonS3Cache/packages.config
tests/ImageProcessor.TestWebsite/ImageProcessor.TestWebsite.csproj
tests/ImageProcessor.TestWebsite/config/imageprocessor/cache.s3.config
tests/ImageProcessor.TestWebsite/config/imageprocessor/security.config

Code for issue #664 to include support for the Amazon S3 Cache.
Builds within Visual Studio 2017 . I've tested using the ImageProcessor.TestWebsite and change the media directory to be /amazon. Within security.config is commented out configuration for S3 and similarly a cahce.s3.config file exists within the chache configuration in that.
Let me know what the next steps are.

#664 Amazon S3 Cache updated

---

src/ImageProcessor.Web/Processors/Crop.cs

Add null and Length guard for crop coordinates

---

src/ImageProcessor.Web/HttpModules/ImageProcessingModule.cs

Adds immutable cache extension when cache busting variables are used

---

src/ImageProcessor.Web/HttpModules/ImageProcessingModule.cs
src/ImageProcessor.Web/Services/IImageService.cs

Introduced `IImageService2` which provides an extra `Task<byte[]> GetImage(object id, HttpContext context);` method.

Add additional context overload. Fix #718

---

ImageProcessor.sln
build/NuSpecs/ImageProcessor.Web.Plugins.AmazonS3Cache.nuspec
build/build.ps1
build/content/ImageProcessor.Web.Plugins.AmazonS3Cache/config/imageprocessor/cache.config.transform
src/ImageProcessor.Web.Plugins.AmazonS3Cache/AmazonS3Cache.cs
src/ImageProcessor.Web.Plugins.AzureBlobCache/AzureBlobCache.cs
src/ImageProcessor.Web/HttpModules/ImageProcessingModule.cs

Adds AmazonS3Cache to the solution and packages.
@AndyFelton If you could review this please and also provide descriptions for each of the config properties that would be great!

WIP Cleanup and add AmazonS3Cache to build

---

src/ImageProcessor.Web/HttpModules/ImageProcessingModule.cs

Only use regex when original is not null. 

---

src/ImageProcessor.Web/HttpModules/ImageProcessingModule.cs

Fixed parsing of Origin header in AddCorsRequestHeaders

---

src/ImageProcessor.Web/Helpers/UrlParser.cs
src/ImageProcessor.Web/HttpModules/ImageProcessingModule.cs

Query string corruption in ImageProcessingModule when using presets

---

build/NuSpecs/ImageProcessor.Web.Plugins.AzureBlobCache.nuspec
src/ImageProcessor.Web.Plugins.AzureBlobCache/AzureBlobCache.cs
src/ImageProcessor.Web.Plugins.AzureBlobCache/AzureImageService.cs
src/ImageProcessor.Web.Plugins.AzureBlobCache/ImageProcessor.Web.Plugins.AzureBlobCache.csproj
src/ImageProcessor.Web.Plugins.AzureBlobCache/app.config
src/ImageProcessor.Web.Plugins.AzureBlobCache/packages.config
tests/ImageProcessor.TestWebsite/Web.config

Updated retired Microsoft.WindowsAzure.Storage & Microsoft.WindowsAzre.ConfigurationManager to Microsoft.Azure.Storage.Blob & Microsoft.Azure.ConfigurationManager respectively
I have tested both the AzureBlobCache and AzureImageService

Update retired WindowsAzure packages
